-- Blog Dr. Márcio — Fase 1. Projeto Supabase COMPARTILHADO com o HD360:
-- todos os objetos são prefixados com mt_ para não colidir com a tabela `posts` do HD360.
-- Aplicar uma vez no SQL Editor do projeto Supabase.

create table if not exists public.mt_posts (
  id               bigint generated by default as identity primary key,
  slug             text not null unique,
  title            text not null,
  date             timestamptz not null default now(),
  modified         timestamptz not null default now(),
  category_name    text not null default '',
  category_color   text not null default '#057f7f',
  cover_image      text default '',
  excerpt          text default '',
  content          text default '',
  meta_description text default '',
  seo_title        text default '',
  og_image         text default '',
  focus_keyword    text default '',
  tags             text[] not null default '{}',
  likes            integer not null default 0,
  status           text not null default 'draft' check (status in ('draft','published','scheduled')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists mt_posts_status_idx on public.mt_posts (status);
create index if not exists mt_posts_date_idx on public.mt_posts (date desc);
create index if not exists mt_posts_scheduled_idx on public.mt_posts (date) where status = 'scheduled';

-- updated_at automático
create or replace function public.mt_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

drop trigger if exists mt_posts_touch_updated_at on public.mt_posts;
create trigger mt_posts_touch_updated_at
  before update on public.mt_posts
  for each row execute function public.mt_touch_updated_at();

-- Curtidas anônimas: incremento seguro só de posts publicados.
create or replace function public.mt_increment_likes(p_slug text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare new_count integer;
begin
  update public.mt_posts
     set likes = likes + 1
   where slug = p_slug and status = 'published'
   returning likes into new_count;
  return coalesce(new_count, 0);
end; $$;

-- RLS
alter table public.mt_posts enable row level security;

drop policy if exists mt_posts_public_read on public.mt_posts;
create policy mt_posts_public_read on public.mt_posts
  for select using (status = 'published');

drop policy if exists mt_posts_admin_all on public.mt_posts;
create policy mt_posts_admin_all on public.mt_posts
  for all to authenticated
  using (true) with check (true);

grant execute on function public.mt_increment_likes(text) to anon, authenticated;
